name: Check Stock Price

on:
  schedule:
    # Run every 10 minutes
    - cron: "*/10 * * * *"
  # workflow_dispatch:  # Allows manual execution from the Actions tab


jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # Specify the Python version you need

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run the Python script
      - name: Run the script
        run: |
          python check_stock_price.py
        
      # Step 5: Capture and fail on null result
      - name: Check for failure in logs
        if: ${{ failure() }}
        run: |
          echo "ERROR: Script encountered a failure. Check logs for details."
          exit 1
